dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/wheels
    - $HOME/.rvm/gems
    - node_modules
python: 3.7
sudo: true
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install jupyter-book
  - npm install gh-pages --save-dev
script: 
  - make install &&  make book && make site
deploy:
  provider: script
  skip_cleanup: true
  keep-history: true
  script: ./.travis_deploy.sh
  on:
    branch: master
