language: python
python: 3.7
virtualenv:
  system_site_packages: true
sudo: required
before_install:
  - sudo apt-get install ruby-full build-essentials zlib1g-dev
install:
  - pip install --user jupyter-book
script: 
  - make install &&  make book
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9d525ff4942a_key -iv $encrypted_9d525ff4942a_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
deploy:
  provider: pages
  local-dir: ./_build
  skip_cleanup: true
  keep-history: true
  on:
    branch: master
