dist: xenial
language: python
cache: pip
python: 3.7
sudo: true
install:
  - pip install jupyter-book
  - npm install gh-pages --save-dev
script: 
  - make install &&  make book
deploy:
  provider: script
  skip_cleanup: true
  keep-history: true
  script: ./.travis_deploy.sh
  on:
    branch: master
