language: generic
sudo: required
before_install:
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --upgrade setuptools
install:
  - pip3 install --user jupyter-book
script: 
  - ls -al ~/.local/bin
  #- make install &&  make book
#before_deploy:
  #- openssl aes-256-cbc -K $encrypted_9d525ff4942a_key -iv $encrypted_9d525ff4942a_iv -in deploy-key.enc -out deploy-key -d
  #- chmod 600 deploy-key
  #- eval `ssh-agent -s`
#deploy:
  #provider: pages
  #local-dir: ./_build
  #skip_cleanup: true
  #keep-history: true
  #on:
    #branch: master
