dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.rvm/gems
    - node_modules
python: 3.7
sudo: true
install:
  - pip install jupyter-book
  - npm install gh-pages --save-dev
script: 
  - make install &&  make book && make site
deploy:
  provider: script
  skip_cleanup: true
  keep-history: true
  script: ./.travis_deploy.sh
  on:
    branch: master
