name: python_kurs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - xarray 
  - pandas
  - rasterio
  - gdal
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - geoviews
  - geopandas
  - fiona
  - h5py
  - netcdf4
  - pyhdf
  - tqdm
  - jupyterlab
  - pillow
  - datashader
  - dask
  - distributed
  - ipywidgets
  - satpy
  - cartopy
  - matplotlib
  - spyder